### ISSUE TITLE
Fix Sobelow vulnerabilities: discovery_streams

### ISSUE THREAD

**Issue by rob-h-m** [smartcitiesdata/discovery_streams#101]
"As an open source code owner, I want to make sure that my applications do not contain security vulnerabilities.

AC:
Running `mix sobelow` does not return any vulnerabilities.
Once all vulnerabilities are addressed, return non-zero exit status at or above a confidence threshold of low (default), medium, or high.

Tech note:
Second AC can be accomplished simply by adding an exit and threshold flag to the `mix sobelow` command in the .travisfile.
https://github.com/nccgroup/sobelow"

Migrated from SMRT-1416

**Comment by ManApart** [comment]
Implemented in #106
